; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??1C24BitBMPpixel@@QEAA@XZ			; C24BitBMPpixel::~C24BitBMPpixel
PUBLIC	??0C24BitBMPpixel@@QEAA@XZ			; C24BitBMPpixel::C24BitBMPpixel
END
