; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

;	COMDAT ?draw_bufers@?1??init@cFBO_RGB_depth@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@4QBIB
CONST	SEGMENT
?draw_bufers@?1??init@cFBO_RGB_depth@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@4QBIB DD 08ce0H ; `cFBO_RGB_depth::init'::`2'::draw_bufers
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
END
