; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?clearDepthBuffer@cFBO_Depth_Only@@QEAAXXZ	; cFBO_Depth_Only::clearDepthBuffer
PUBLIC	?init@cFBO_Depth_Only@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ; cFBO_Depth_Only::init
;	COMDAT pdata
pdata	SEGMENT
$pdata$?clearDepthBuffer@cFBO_Depth_Only@@QEAAXXZ DD imagerel $LN4@clearDepth
	DD	imagerel $LN4@clearDepth+116
	DD	imagerel $unwind$?clearDepthBuffer@cFBO_Depth_Only@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?init@cFBO_Depth_Only@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DD imagerel $LN29@init
	DD	imagerel $LN29@init+395
	DD	imagerel $unwind$?init@cFBO_Depth_Only@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?init@cFBO_Depth_Only@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DQ 0000e640f00061e19r ; 2.00129e-308
	DQ	0700b920f000d340fr		; 5.35047e+231
	DD	imagerel __GSHandlerCheck
	DD	040H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?clearDepthBuffer@cFBO_Depth_Only@@QEAAXXZ DQ 00000620400011319r ; 5.32451e-310
	DD	imagerel __GSHandlerCheck
	DD	028H
END
