; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BD@DPMDOJJG@Could?5not?5shutdown@	; `string'
PUBLIC	??_C@_0CF@IFCLKBII@GL_FRAMEBUFFER_INCOMPLETE_ATTAC@ ; `string'
;	COMDAT ?draw_bufers@?1??init@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@4QBIB
CONST	SEGMENT
?draw_bufers@?1??init@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@4QBIB DD 08ce0H ; `cFBO_deferred::init'::`2'::draw_bufers
	DD	08ce1H
	DD	08ce2H
	DD	08ce3H
CONST	ENDS
;	COMDAT ??_C@_0CF@IFCLKBII@GL_FRAMEBUFFER_INCOMPLETE_ATTAC@
CONST	SEGMENT
??_C@_0CF@IFCLKBII@GL_FRAMEBUFFER_INCOMPLETE_ATTAC@ DB 'GL_FRAMEBUFFER_IN'
	DB	'COMPLETE_ATTACHMENT', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@DPMDOJJG@Could?5not?5shutdown@
CONST	SEGMENT
??_C@_0BD@DPMDOJJG@Could?5not?5shutdown@ DB 'Could not shutdown', 00H ; `string'
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?init@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ; cFBO_deferred::init
PUBLIC	?shutdown@cFBO_deferred@@QEAA_NXZ		; cFBO_deferred::shutdown
PUBLIC	?reset@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z ; cFBO_deferred::reset
;	COMDAT pdata
pdata	SEGMENT
$pdata$?init@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DD imagerel $LN23@init
	DD	imagerel $LN23@init+787
	DD	imagerel $unwind$?init@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?shutdown@cFBO_deferred@@QEAA_NXZ DD imagerel $LN4@shutdown
	DD	imagerel $LN4@shutdown+106
	DD	imagerel $unwind$?shutdown@cFBO_deferred@@QEAA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?reset@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DD imagerel $LN14@reset
	DD	imagerel $LN14@reset+109
	DD	imagerel $unwind$?reset@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?reset@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?shutdown@cFBO_deferred@@QEAA_NXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?init@cFBO_deferred@@QEAA_NHHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z DQ 0000d741e000c1e01r ; 1.87095e-308
	DQ	0000b541e000c641er		; 1.57543e-308
	DQ	0f01a521e000a341er		; -1.02159e+232
	DD	0c016e018H
END
