; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BC@MBJEGPNE@Jet?5back?5enabled?$CB@	; `string'
;	COMDAT ??_C@_0BC@MBJEGPNE@Jet?5back?5enabled?$CB@
CONST	SEGMENT
??_C@_0BC@MBJEGPNE@Jet?5back?5enabled?$CB@ DB 'Jet back enabled!', 00H ; `string'
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
END
