; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?DEFAULTZEROTHRESHOLD@cLightHelper@@2MB		; cLightHelper::DEFAULTZEROTHRESHOLD
?DEFAULTZEROTHRESHOLD@cLightHelper@@2MB DD 038d1b717r ; 0.0001 ; cLightHelper::DEFAULTZEROTHRESHOLD
PUBLIC	?calcDiffuseFromAttenByDistance@cLightHelper@@QEAAMMMMMM@Z ; cLightHelper::calcDiffuseFromAttenByDistance
PUBLIC	?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z ; cLightHelper::calcApproxDistFromAtten
;	COMDAT pdata
pdata	SEGMENT
$pdata$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z DD imagerel $LN37@calcApprox
	DD	imagerel $LN37@calcApprox+214
	DD	imagerel $unwind$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z DD imagerel $LN37@calcApprox+214
	DD	imagerel $LN37@calcApprox+357
	DD	imagerel $chain$0$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z DD imagerel $LN37@calcApprox+357
	DD	imagerel $LN37@calcApprox+395
	DD	imagerel $chain$1$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z DD 021H
	DD	imagerel $LN37@calcApprox
	DD	imagerel $LN37@calcApprox+214
	DD	imagerel $unwind$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z DQ 00003980600020621r ; 4.99785e-309
	DD	imagerel $LN37@calcApprox
	DD	imagerel $LN37@calcApprox+214
	DD	imagerel $unwind$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?calcApproxDistFromAtten@cLightHelper@@QEAAMMMMMMMI@Z DQ 00000c82e000d2e01r ; 1.08744e-309
	DQ	00002a8230001b829r		; 3.69471e-309
	DQ	0000578110004881dr		; 7.60559e-309
	DQ	00000e20400066809r		; 1.22779e-309
END
