; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	??$_Copy_memmove_tail@PEAN@std@@YAPEANQEBDQEAN_K2@Z ; std::_Copy_memmove_tail<double *>
PUBLIC	??$move@AEAPEAN@std@@YA$$QEAPEANAEAPEAN@Z	; std::move<double * &>
PUBLIC	??$_Emplace_back@N@?$_Uninitialized_backout_al@V?$allocator@N@std@@@std@@QEAAX$$QEAN@Z ; std::_Uninitialized_backout_al<std::allocator<double> >::_Emplace_back<double>
PUBLIC	??$_To_address@PEAN@std@@YA?A_PAEBQEAN@Z	; std::_To_address<double *>
PUBLIC	??$_Copy_memmove@PEANPEAN@std@@YAPEANPEAN00@Z	; std::_Copy_memmove<double *,double *>
PUBLIC	??$addressof@N@std@@YAPEANAEAN@Z		; std::addressof<double>
PUBLIC	?allocate@?$allocator@N@std@@QEAAPEAN_K@Z	; std::allocator<double>::allocate
PUBLIC	??0?$_Uninitialized_backout_al@V?$allocator@N@std@@@std@@QEAA@PEANAEAV?$allocator@N@1@@Z ; std::_Uninitialized_backout_al<std::allocator<double> >::_Uninitialized_backout_al<std::allocator<double> >
PUBLIC	??1?$_Uninitialized_backout_al@V?$allocator@N@std@@@std@@QEAA@XZ ; std::_Uninitialized_backout_al<std::allocator<double> >::~_Uninitialized_backout_al<std::allocator<double> >
PUBLIC	?_Release@?$_Uninitialized_backout_al@V?$allocator@N@std@@@std@@QEAAPEANXZ ; std::_Uninitialized_backout_al<std::allocator<double> >::_Release
PUBLIC	?__autoclassinit2@?$_Uninitialized_backout_al@V?$allocator@N@std@@@std@@QEAAX_K@Z ; std::_Uninitialized_backout_al<std::allocator<double> >::__autoclassinit2
PUBLIC	??$_Uninitialized_move@PEANV?$allocator@N@std@@@std@@YAPEANQEAN0PEANAEAV?$allocator@N@0@@Z ; std::_Uninitialized_move<double *,std::allocator<double> >
PUBLIC	??$_Get_unwrapped@AEBQEAN@std@@YA?A_TAEBQEAN@Z	; std::_Get_unwrapped<double * const &>
PUBLIC	??$construct@NN@?$_Default_allocator_traits@V?$allocator@N@std@@@std@@SAXAEAV?$allocator@N@1@QEAN$$QEAN@Z ; std::_Default_allocator_traits<std::allocator<double> >::construct<double,double>
PUBLIC	??$_Unfancy@N@std@@YAPEANPEAN@Z			; std::_Unfancy<double>
PUBLIC	??$_Allocate_at_least_helper@V?$allocator@N@std@@@std@@YAPEANAEAV?$allocator@N@0@AEA_K@Z ; std::_Allocate_at_least_helper<std::allocator<double> >
PUBLIC	??$_Construct_in_place@NN@std@@YAXAEAN$$QEAN@Z	; std::_Construct_in_place<double,double>
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@N@std@@V?$_Vector_val@U?$_Simple_types@N@std@@@2@$00@std@@QEBAAEBV?$allocator@N@2@XZ ; std::_Compressed_pair<std::allocator<double>,std::_Vector_val<std::_Simple_types<double> >,1>::_Get_first
PUBLIC	?max_size@?$_Default_allocator_traits@V?$allocator@N@std@@@std@@SA_KAEBV?$allocator@N@2@@Z ; std::_Default_allocator_traits<std::allocator<double> >::max_size
PUBLIC	?capacity@?$vector@NV?$allocator@N@std@@@std@@QEBA_KXZ ; std::vector<double,std::allocator<double> >::capacity
PUBLIC	?_Getal@?$vector@NV?$allocator@N@std@@@std@@AEBAAEBV?$allocator@N@2@XZ ; std::vector<double,std::allocator<double> >::_Getal
PUBLIC	?max_size@?$vector@NV?$allocator@N@std@@@std@@QEBA_KXZ ; std::vector<double,std::allocator<double> >::max_size
PUBLIC	?_Calculate_growth@?$vector@NV?$allocator@N@std@@@std@@AEBA_K_K@Z ; std::vector<double,std::allocator<double> >::_Calculate_growth
PUBLIC	?_Change_array@?$vector@NV?$allocator@N@std@@@std@@AEAAXQEAN_K1@Z ; std::vector<double,std::allocator<double> >::_Change_array
PUBLIC	?_Xlength@?$vector@NV?$allocator@N@std@@@std@@CAXXZ ; std::vector<double,std::allocator<double> >::_Xlength
PUBLIC	?_Orphan_range@?$vector@NV?$allocator@N@std@@@std@@AEBAXPEAN0@Z ; std::vector<double,std::allocator<double> >::_Orphan_range
PUBLIC	??1_Reallocation_guard@?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ ; std::vector<double,std::allocator<double> >::_Reallocation_guard::~_Reallocation_guard
PUBLIC	??$move@AEAV?$allocator@N@std@@@std@@YA$$QEAV?$allocator@N@0@AEAV10@@Z ; std::move<std::allocator<double> &>
PUBLIC	??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z ; std::vector<double,std::allocator<double> >::_Emplace_reallocate<double>
PUBLIC	??$_Emplace_back_with_unused_capacity@N@?$vector@NV?$allocator@N@std@@@std@@AEAAAEAN$$QEAN@Z ; std::vector<double,std::allocator<double> >::_Emplace_back_with_unused_capacity<double>
PUBLIC	??$forward@N@std@@YA$$QEANAEAN@Z		; std::forward<double>
PUBLIC	??0?$allocator@N@std@@QEAA@XZ			; std::allocator<double>::allocator<double>
PUBLIC	??0?$_Vector_val@U?$_Simple_types@N@std@@@std@@QEAA@XZ ; std::_Vector_val<std::_Simple_types<double> >::_Vector_val<std::_Simple_types<double> >
PUBLIC	??$_Destroy_range@V?$allocator@N@std@@@std@@YAXPEANQEANAEAV?$allocator@N@0@@Z ; std::_Destroy_range<std::allocator<double> >
PUBLIC	??$?0$$V@?$_Compressed_pair@V?$allocator@N@std@@V?$_Vector_val@U?$_Simple_types@N@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ; std::_Compressed_pair<std::allocator<double>,std::_Vector_val<std::_Simple_types<double> >,1>::_Compressed_pair<std::allocator<double>,std::_Vector_val<std::_Simple_types<double> >,1><>
PUBLIC	??$_Pocma@V?$allocator@N@std@@@std@@YAXAEAV?$allocator@N@0@0@Z ; std::_Pocma<std::allocator<double> >
PUBLIC	??$addressof@V?$vector@NV?$allocator@N@std@@@std@@@std@@YAPEAV?$vector@NV?$allocator@N@std@@@0@AEAV10@@Z ; std::addressof<std::vector<double,std::allocator<double> > >
PUBLIC	??$_Emplace_one_at_back@N@?$vector@NV?$allocator@N@std@@@std@@AEAAAEAN$$QEAN@Z ; std::vector<double,std::allocator<double> >::_Emplace_one_at_back<double>
PUBLIC	??$move@AEAN@std@@YA$$QEANAEAN@Z		; std::move<double &>
PUBLIC	??$addressof@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@YAPEAV?$_Vector_val@U?$_Simple_types@N@std@@@0@AEAV10@@Z ; std::addressof<std::_Vector_val<std::_Simple_types<double> > >
PUBLIC	??$_Unfancy_maybe_null@N@std@@YAPEANPEAN@Z	; std::_Unfancy_maybe_null<double>
PUBLIC	?deallocate@?$allocator@N@std@@QEAAXQEAN_K@Z	; std::allocator<double>::deallocate
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@N@std@@V?$_Vector_val@U?$_Simple_types@N@std@@@2@$00@std@@QEAAAEAV?$allocator@N@2@XZ ; std::_Compressed_pair<std::allocator<double>,std::_Vector_val<std::_Simple_types<double> >,1>::_Get_first
PUBLIC	?_Tidy@?$vector@NV?$allocator@N@std@@@std@@AEAAXXZ ; std::vector<double,std::allocator<double> >::_Tidy
PUBLIC	?_Getal@?$vector@NV?$allocator@N@std@@@std@@AEAAAEAV?$allocator@N@2@XZ ; std::vector<double,std::allocator<double> >::_Getal
PUBLIC	?_Take_contents@?$_Vector_val@U?$_Simple_types@N@std@@@std@@QEAAXAEAV12@@Z ; std::_Vector_val<std::_Simple_types<double> >::_Take_contents
PUBLIC	??0?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAA@PEANPEBU_Container_base0@1@@Z ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >
PUBLIC	??D?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEBAAEBNXZ ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >::operator*
PUBLIC	??E?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAAAEAV01@XZ ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >::operator++
PUBLIC	?_Compat@?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEBAXAEBV12@@Z ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >::_Compat
PUBLIC	??0?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAA@PEANPEBU_Container_base0@1@@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >
PUBLIC	?__autoclassinit2@?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAAX_K@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >::__autoclassinit2
PUBLIC	??0?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ	; std::vector<double,std::allocator<double> >::vector<double,std::allocator<double> >
PUBLIC	??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z ; std::vector<double,std::allocator<double> >::operator=
PUBLIC	??1?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ	; std::vector<double,std::allocator<double> >::~vector<double,std::allocator<double> >
PUBLIC	?push_back@?$vector@NV?$allocator@N@std@@@std@@QEAAX$$QEAN@Z ; std::vector<double,std::allocator<double> >::push_back
PUBLIC	?begin@?$vector@NV?$allocator@N@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@2@XZ ; std::vector<double,std::allocator<double> >::begin
PUBLIC	?end@?$vector@NV?$allocator@N@std@@@std@@QEAA?AV?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@2@XZ ; std::vector<double,std::allocator<double> >::end
PUBLIC	?_Unchecked_begin@?$vector@NV?$allocator@N@std@@@std@@QEAAPEANXZ ; std::vector<double,std::allocator<double> >::_Unchecked_begin
PUBLIC	?_Unchecked_end@?$vector@NV?$allocator@N@std@@@std@@QEAAPEANXZ ; std::vector<double,std::allocator<double> >::_Unchecked_end
PUBLIC	??0?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAA@XZ ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >
PUBLIC	??8?$_Vector_const_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEBA_NAEBV01@@Z ; std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<double> > >::operator==
PUBLIC	??D?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEBAAEANXZ ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >::operator*
PUBLIC	??E?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAA?AV01@H@Z ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >::operator++
PUBLIC	?getAverage@cLowPassFilter@@QEAANXZ		; cLowPassFilter::getAverage
PUBLIC	?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ	; cLowPassFilter::m_ResizeSampleVector
PUBLIC	?addSample@cLowPassFilter@@QEAAXN@Z		; cLowPassFilter::addSample
PUBLIC	??0?$_Vector_iterator@V?$_Vector_val@U?$_Simple_types@N@std@@@std@@@std@@QEAA@XZ ; std::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >::_Vector_iterator<std::_Vector_val<std::_Simple_types<double> > >
PUBLIC	??0cLowPassFilter@@QEAA@XZ			; cLowPassFilter::cLowPassFilter
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Copy_memmove_tail@PEAN@std@@YAPEANQEBDQEAN_K2@Z DD imagerel $LN4@Copy_memmo
	DD	imagerel $LN4@Copy_memmo+42
	DD	imagerel $unwind$??$_Copy_memmove_tail@PEAN@std@@YAPEANQEBDQEAN_K2@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Copy_memmove@PEANPEAN@std@@YAPEANPEAN00@Z DD imagerel $LN6@Copy_memmo
	DD	imagerel $LN6@Copy_memmo+48
	DD	imagerel $unwind$??$_Copy_memmove@PEANPEAN@std@@YAPEANPEAN00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?allocate@?$allocator@N@std@@QEAAPEAN_K@Z DD imagerel $LN31@allocate
	DD	imagerel $LN31@allocate+112
	DD	imagerel $unwind$?allocate@?$allocator@N@std@@QEAAPEAN_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_move@PEANV?$allocator@N@std@@@std@@YAPEANQEAN0PEANAEAV?$allocator@N@0@@Z DD imagerel $LN23@Uninitiali
	DD	imagerel $LN23@Uninitiali+52
	DD	imagerel $unwind$??$_Uninitialized_move@PEANV?$allocator@N@std@@@std@@YAPEANQEAN0PEANAEAV?$allocator@N@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Allocate_at_least_helper@V?$allocator@N@std@@@std@@YAPEANAEAV?$allocator@N@0@AEA_K@Z DD imagerel $LN34@Allocate_a
	DD	imagerel $LN34@Allocate_a+115
	DD	imagerel $unwind$??$_Allocate_at_least_helper@V?$allocator@N@std@@@std@@YAPEANAEAV?$allocator@N@0@AEA_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Change_array@?$vector@NV?$allocator@N@std@@@std@@AEAAXQEAN_K1@Z DD imagerel $LN31@Change_arr
	DD	imagerel $LN31@Change_arr+136
	DD	imagerel $unwind$?_Change_array@?$vector@NV?$allocator@N@std@@@std@@AEAAXQEAN_K1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Xlength@?$vector@NV?$allocator@N@std@@@std@@CAXXZ DD imagerel $LN4@Xlength
	DD	imagerel $LN4@Xlength+18
	DD	imagerel $unwind$?_Xlength@?$vector@NV?$allocator@N@std@@@std@@CAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1_Reallocation_guard@?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ DD imagerel $LN28@Reallocati
	DD	imagerel $LN28@Reallocati+78
	DD	imagerel $unwind$??1_Reallocation_guard@?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DD imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DD imagerel $LN176@Emplace_re+70
	DD	imagerel $LN176@Emplace_re+381
	DD	imagerel $chain$2$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DD imagerel $LN176@Emplace_re+381
	DD	imagerel $LN176@Emplace_re+388
	DD	imagerel $chain$4$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DD imagerel $LN176@Emplace_re+388
	DD	imagerel $LN176@Emplace_re+394
	DD	imagerel $chain$5$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DD imagerel $LN176@Emplace_re+394
	DD	imagerel $LN176@Emplace_re+400
	DD	imagerel $chain$6$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?deallocate@?$allocator@N@std@@QEAAXQEAN_K@Z DD imagerel $LN23@deallocate
	DD	imagerel $LN23@deallocate+67
	DD	imagerel $unwind$?deallocate@?$allocator@N@std@@QEAAXQEAN_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Tidy@?$vector@NV?$allocator@N@std@@@std@@AEAAXXZ DD imagerel $LN31@Tidy
	DD	imagerel $LN31@Tidy+92
	DD	imagerel $unwind$?_Tidy@?$vector@NV?$allocator@N@std@@@std@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DD imagerel $LN42@operator
	DD	imagerel $LN42@operator+24
	DD	imagerel $unwind$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DD imagerel $LN42@operator+24
	DD	imagerel $LN42@operator+134
	DD	imagerel $chain$0$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DD imagerel $LN42@operator+134
	DD	imagerel $LN42@operator+148
	DD	imagerel $chain$1$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DD imagerel $LN42@operator+148
	DD	imagerel $LN42@operator+155
	DD	imagerel $chain$2$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ DD imagerel $LN35@vector
	DD	imagerel $LN35@vector+92
	DD	imagerel $unwind$??1?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DD imagerel $LN111@m_ResizeSa
	DD	imagerel $LN111@m_ResizeSa+98
	DD	imagerel $unwind$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DD imagerel $LN111@m_ResizeSa+98
	DD	imagerel $LN111@m_ResizeSa+151
	DD	imagerel $chain$0$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DD imagerel $LN111@m_ResizeSa+151
	DD	imagerel $LN111@m_ResizeSa+158
	DD	imagerel $chain$1$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DD imagerel $LN111@m_ResizeSa+158
	DD	imagerel $LN111@m_ResizeSa+206
	DD	imagerel $chain$2$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0cLowPassFilter@@QEAA@XZ DD imagerel $LN21@cLowPassFi
	DD	imagerel $LN21@cLowPassFi+52
	DD	imagerel $unwind$??0cLowPassFilter@@QEAA@XZ
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0cLowPassFilter@@QEAA@XZ DW 04a02H
	DB	02H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0cLowPassFilter@@QEAA@XZ DW 0c02H
	DD	imagerel ??1?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ
	DB	060H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??0cLowPassFilter@@QEAA@XZ DB 028H
	DD	imagerel $stateUnwindMap$??0cLowPassFilter@@QEAA@XZ
	DD	imagerel $ip2state$??0cLowPassFilter@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0cLowPassFilter@@QEAA@XZ DQ 03006320a00020a11r ; 2.39605e-77
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??0cLowPassFilter@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DQ 0000b740000020021r ; 1.59275e-308
	DD	imagerel $LN111@m_ResizeSa
	DD	imagerel $LN111@m_ResizeSa+98
	DD	imagerel $unwind$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DD 021H
	DD	imagerel $LN111@m_ResizeSa
	DD	imagerel $LN111@m_ResizeSa+98
	DD	imagerel $unwind$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DQ 0000b740500020521r ; 1.59276e-308
	DD	imagerel $LN111@m_ResizeSa
	DD	imagerel $LN111@m_ResizeSa+98
	DD	imagerel $unwind$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?m_ResizeSampleVector@cLowPassFilter@@AEAAXXZ DQ 0000d540f00060f01r ; 1.85354e-308
	DQ	0600b720f000c340fr		; 4.59981e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DQ 00008640000020021r ; 1.16686e-308
	DD	imagerel $LN42@operator
	DD	imagerel $LN42@operator+24
	DD	imagerel $unwind$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DD 021H
	DD	imagerel $LN42@operator
	DD	imagerel $LN42@operator+24
	DD	imagerel $unwind$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DQ 00008640500020521r ; 1.16687e-308
	DD	imagerel $LN42@operator
	DD	imagerel $LN42@operator+24
	DD	imagerel $unwind$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??4?$vector@NV?$allocator@N@std@@@std@@QEAAAEAV01@$$QEAV01@@Z DQ 00009340a00040a01r ; 1.27987e-308
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Tidy@?$vector@NV?$allocator@N@std@@@std@@AEAAXXZ DQ 03002320600020601r ; 1.96423e-77
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?deallocate@?$allocator@N@std@@QEAAXQEAN_K@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DQ 00004f40000060021r ; 6.88817e-309
	DQ	0000c3400000d6400r		; 1.69705e-308
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DD 021H
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DQ 00004f40000060021r ; 6.88817e-309
	DQ	0000c3400000d6400r		; 1.69705e-308
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DQ 00004f41900061921r ; 6.8887e-309
	DQ	0000c3405000d640er		; 1.69706e-308
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Emplace_reallocate@N@?$vector@NV?$allocator@N@std@@@std@@AEAAPEANQEAN$$QEAN@Z DQ 0e007420b00050b01r ; -3.89798e+154
	DQ	0000050027003c005r		; 4.34636e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1_Reallocation_guard@?$vector@NV?$allocator@N@std@@@std@@QEAA@XZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Xlength@?$vector@NV?$allocator@N@std@@@std@@CAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Change_array@?$vector@NV?$allocator@N@std@@@std@@AEAAXQEAN_K1@Z DQ 00009641400081401r ; 1.30597e-308
	DQ	00007341400085414r		; 1.00176e-308
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Allocate_at_least_helper@V?$allocator@N@std@@@std@@YAPEANAEAV?$allocator@N@0@AEA_K@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_move@PEANV?$allocator@N@std@@@std@@YAPEANQEAN0PEANAEAV?$allocator@N@0@@Z DQ 00009340a00040a01r ; 1.27987e-308
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?allocate@?$allocator@N@std@@QEAAPEAN_K@Z DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Copy_memmove@PEANPEAN@std@@YAPEANPEAN00@Z DQ 00009340a00040a01r ; 1.27987e-308
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Copy_memmove_tail@PEAN@std@@YAPEANQEBDQEAN_K2@Z DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
END
