; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	??R?$divides@M@std@@QEBAMAEBM0@Z		; std::divides<float>::operator()
PUBLIC	??$call@U?$divides@M@std@@@?$functor2@Uvec@glm@@$02M$0A@@detail@glm@@SA?AU?$vec@$02M$0A@@2@U?$divides@M@std@@AEBU32@1@Z ; glm::detail::functor2<glm::vec,3,float,0>::call<std::divides<float> >
PUBLIC	?call@?$compute_vec_div@$02M$0A@$0A@@detail@glm@@SA?AU?$vec@$02M$0A@@3@AEBU43@0@Z ; glm::detail::compute_vec_div<3,float,0,0>::call
PUBLIC	??$?_0M@?$vec@$02M$0A@@glm@@QEAAAEAU01@M@Z	; glm::vec<3,float,0>::operator/=<float>
PUBLIC	??$?KM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@M@Z ; glm::operator/<float,0>
PUBLIC	?OnFinished@cMoveRelativeTime@@UEAAXXZ		; cMoveRelativeTime::OnFinished
PUBLIC	?isFinished@cMoveRelativeTime@@UEAA_NXZ		; cMoveRelativeTime::isFinished
PUBLIC	?Update@cMoveRelativeTime@@UEAAXN@Z		; cMoveRelativeTime::Update
PUBLIC	?OnStart@cMoveRelativeTime@@UEAAXXZ		; cMoveRelativeTime::OnStart
PUBLIC	?Init@cMoveRelativeTime@@QEAAXPEAUsPhysInfo@cPhysics@@U?$vec@$02M$0A@@glm@@N@Z ; cMoveRelativeTime::Init
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?KM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@M@Z DD imagerel $LN20@operator
	DD	imagerel $LN20@operator+60
	DD	imagerel $unwind$??$?KM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@M@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?OnStart@cMoveRelativeTime@@UEAAXXZ DD imagerel $LN38@OnStart
	DD	imagerel $LN38@OnStart+110
	DD	imagerel $unwind$?OnStart@cMoveRelativeTime@@UEAAXXZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$?OnStart@cMoveRelativeTime@@UEAAXXZ DQ 00000420400010401r ; 3.58617e-310
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?KM$0A@@glm@@YA?AU?$vec@$02M$0A@@0@AEBU10@M@Z DQ 00000220400010401r ; 1.84783e-310
END
