; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_06JMDFGJPK@?$DM?5mesh@			; `string'
PUBLIC	??_C@_0N@JEHCOCMP@Can?8t?5find?5?$DO@		; `string'
;	COMDAT ??_C@_0N@JEHCOCMP@Can?8t?5find?5?$DO@
CONST	SEGMENT
??_C@_0N@JEHCOCMP@Can?8t?5find?5?$DO@ DB 'Can''t find >', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_06JMDFGJPK@?$DM?5mesh@
CONST	SEGMENT
??_C@_06JMDFGJPK@?$DM?5mesh@ DB '< mesh', 00H		; `string'
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
?piecewise_construct@std@@3Upiecewise_construct_t@1@B	ORG $+1 ; std::piecewise_construct
PUBLIC	??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z ; std::operator+<char,std::char_traits<char>,std::allocator<char> >
PUBLIC	?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z	; cPhysics::updateSoftBodyMeshes
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z DD imagerel $LN43@operator
	DD	imagerel $LN43@operator+109
	DD	imagerel $unwind$??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z DD imagerel $LN227@updateSoft
	DD	imagerel $LN227@updateSoft+729
	DD	imagerel $unwind$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z DQ 0460402f902034508r ; 1.98185e+29
	DD	03b902H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z DW 0a04H
	DD	imagerel ??1sModelDrawInfo@@QEAA@XZ
	DW	034a0H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DB	040H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z DB 028H
	DD	imagerel $stateUnwindMap$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z
	DD	imagerel $ip2state$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z DQ 0000f6827000f3519r ; 2.14259e-308
	DQ	00027642300287423r		; 6.50588e-308
	DQ	00020012300263423r		; 4.45138e-308
	DQ	0c012d014e016f018r		; -4.7032
	DD	05010H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?updateSoftBodyMeshes@cPhysics@@QEAAXI@Z
	DD	0e2H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?HDU?$char_traits@D@std@@V?$allocator@D@1@@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@$$QEAV10@QEBD@Z DQ 00008340a00040a01r ; 1.14081e-308
	DD	07006520aH
END
