; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BK@PGDKCGKF@Rail?5gun?5goes?3?5pew?$CB?5Zapp?$CB@ ; `string'
;	COMDAT ??_C@_0BK@PGDKCGKF@Rail?5gun?5goes?3?5pew?$CB?5Zapp?$CB@
CONST	SEGMENT
??_C@_0BK@PGDKCGKF@Rail?5gun?5goes?3?5pew?$CB?5Zapp?$CB@ DB 'Rail gun goe'
	DB	's: pew! Zapp!', 00H				; `string'
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?Shoot@cRailGun@@QEAAXPEAViTank@@@Z		; cRailGun::Shoot
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Shoot@cRailGun@@QEAAXPEAViTank@@@Z DD imagerel $LN4@Shoot
	DD	imagerel $LN4@Shoot+44
	DD	imagerel $unwind$?Shoot@cRailGun@@QEAAXPEAViTank@@@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Shoot@cRailGun@@QEAAXPEAViTank@@@Z DQ 00000420400010401r ; 3.58617e-310
END
