; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_R2cSheild@@8					; cSheild::`RTTI Base Class Array'
PUBLIC	??_R4cSheild@@6B@				; cSheild::`RTTI Complete Object Locator'
PUBLIC	??_7cSheild@@6B@				; cSheild::`vftable'
PUBLIC	??_R1A@?0A@EA@cSheild@@8			; cSheild::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R3cSheild@@8					; cSheild::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R0?AVcSheild@@@8				; cSheild `RTTI Type Descriptor'
;	COMDAT ??_R0?AVcSheild@@@8
data$rs	SEGMENT
??_R0?AVcSheild@@@8 DQ FLAT:??_7type_info@@6B@		; cSheild `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVcSheild@@', 00H
data$rs	ENDS
;	COMDAT ??_R3cSheild@@8
rdata$r	SEGMENT
??_R3cSheild@@8 DD 00H					; cSheild::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2cSheild@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@cSheild@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@cSheild@@8 DD imagerel ??_R0?AVcSheild@@@8 ; cSheild::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3cSheild@@8
rdata$r	ENDS
;	COMDAT ??_7cSheild@@6B@
CONST	SEGMENT
??_7cSheild@@6B@ DQ FLAT:??_R4cSheild@@6B@		; cSheild::`vftable'
	DQ	FLAT:??_EcSheild@@UEAAPEAXI@Z
	DQ	FLAT:?Receive_Message@cSheild@@UEAA_NUsNVPair@@@Z
	DQ	FLAT:?Send_Message@cSheild@@UEAA_NUsNVPair@@@Z
CONST	ENDS
;	COMDAT ??_R4cSheild@@6B@
rdata$r	SEGMENT
??_R4cSheild@@6B@ DD 01H				; cSheild::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVcSheild@@@8
	DD	imagerel ??_R3cSheild@@8
	DD	imagerel ??_R4cSheild@@6B@
rdata$r	ENDS
;	COMDAT ??_R2cSheild@@8
rdata$r	SEGMENT
??_R2cSheild@@8 DD imagerel ??_R1A@?0A@EA@cSheild@@8	; cSheild::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@iMessaging@@8
	ORG $+3
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	??1cSheild@@UEAA@XZ				; cSheild::~cSheild
PUBLIC	??_GcSheild@@UEAAPEAXI@Z			; cSheild::`scalar deleting destructor'
EXTRN	??_EcSheild@@UEAAPEAXI@Z:PROC			; cSheild::`vector deleting destructor'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_GcSheild@@UEAAPEAXI@Z DD imagerel $LN9@scalar
	DD	imagerel $LN9@scalar+43
	DD	imagerel $unwind$??_GcSheild@@UEAAPEAXI@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_GcSheild@@UEAAPEAXI@Z DQ 03002320600020601r ; 1.96423e-77
END
