; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?setTerrainMesh@cTerrainPathChooser@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$02M$0A@@glm@@@Z ; cTerrainPathChooser::setTerrainMesh
PUBLIC	??0cTerrainPathChooser@@QEAA@PEAVcVAOManager@@@Z ; cTerrainPathChooser::cTerrainPathChooser
;	COMDAT pdata
pdata	SEGMENT
$pdata$?setTerrainMesh@cTerrainPathChooser@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$02M$0A@@glm@@@Z DD imagerel $LN52@setTerrain
	DD	imagerel $LN52@setTerrain+95
	DD	imagerel $unwind$?setTerrainMesh@cTerrainPathChooser@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$02M$0A@@glm@@@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?setTerrainMesh@cTerrainPathChooser@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$vec@$02M$0A@@glm@@@Z DQ 03002320600020601r ; 1.96423e-77
END
