; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
?piecewise_construct@std@@3Upiecewise_construct_t@1@B	ORG $+1 ; std::piecewise_construct
PUBLIC	?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z ; cVAOManager::UpdateDynamicMesh
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z DD imagerel $LN45@UpdateDyna
	DD	imagerel $LN45@UpdateDyna+182
	DD	imagerel $unwind$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z DD 03e025a04H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z DW 0c02H
	DD	imagerel ??1?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@XZ
	DB	040H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z DB 028H
	DD	imagerel $stateUnwindMap$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z
	DD	imagerel $ip2state$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z DQ 00008340a00041919r ; 1.14081e-308
	DD	07006520aH
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$?UpdateDynamicMesh@cVAOManager@@QEAA_NV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAUsModelDrawInfo@@I@Z
	DD	02aH
END
