; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34808.0 

include listing.inc

INCLUDELIB OLDNAMES

?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?UpdateFlagLocation@cViperFlagConnector@@QEAAXXZ ; cViperFlagConnector::UpdateFlagLocation
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateFlagLocation@cViperFlagConnector@@QEAAXXZ DD imagerel $LN100@UpdateFlag
	DD	imagerel $LN100@UpdateFlag+214
	DD	imagerel $unwind$?UpdateFlagLocation@cViperFlagConnector@@QEAAXXZ
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateFlagLocation@cViperFlagConnector@@QEAAXXZ DQ 00001781700051701r ; 2.04304e-309
	DQ	0000062040002680fr		; 5.32451e-310
END
